name: testing actions on Azure
 on:  
 push:
   branches: 
    - master
jobs:
 remove:
  runs-on: [self-hosted, linux, x64]
  steps:
   - name: remove the container hosted on port 3000
     run: |
       cd 
       cd docker/node-app
       PORT=3000
       id=`docker container ls --format="{{.ID}}\t{{.Ports}}" | grep $PORT | awk '{print $1}'`
       docker stop $id
       docker rm $id
       docker rmi node-app
       echo "successfully removed container"
 build:
  runs-on: [self-hosted, linux, x64] 
  needs: remove
  steps:
   - name: Build new image
     run: |
      cd 
      cd docker/node-app
      docker build -t node-app .
      echo "successfully created image"
 create:
  runs-on: [self-hosted, linux, x64] 
  needs: build
  steps:
   - name: Create a container
     run: |
      cd 
      cd docker/node-app
      docker run -d --name nodeapp -p 3000:3000 node-app
      echo "successfully created container"
